u1 = User.create(username: "coolguy58", email: "fakeemail@fake.com", password: "password", bio: "I'm the coolest!")
u2 = User.create(username: "the_best", email: "totallyrealemail@fake.com", password: "drowssap", bio: "I'm the best!")
u3 = User.create(username: "the_worst", email: "totallyrealemail@fake.com", password: "drowssap", bio: "I'm the worst...")

i1 = Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
i2 = Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
i3 = Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
i4 = Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
i5 = Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
i6 = Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)
Image.create(title: "example", url: "https://via.placeholder.com/350x150", user_id: u1.id)
Image.create(title: "example", url: "https://via.placeholder.com/200x200", user_id: u2.id)
Image.create(title: "example", url: "https://via.placeholder.com/400x700", user_id: u3.id)

Favorite.create(user_id: u2.id, image_id: i1.id)
Favorite.create(user_id: u3.id, image_id: i1.id)
Favorite.create(user_id: u1.id, image_id: i2.id)
Favorite.create(user_id: u2.id, image_id: i3.id)
Favorite.create(user_id: u3.id, image_id: i2.id)
Favorite.create(user_id: u1.id, image_id: i3.id)
Like.create(user_id: u2.id, image_id: i1.id)
Like.create(user_id: u3.id, image_id: i1.id)
Like.create(user_id: u1.id, image_id: i5.id)
Like.create(user_id: u2.id, image_id: i6.id)
Like.create(user_id: u1.id, image_id: i6.id)
Like.create(user_id: u3.id, image_id: i4.id)
Dislike.create(user_id: u3.id, image_id: i2.id)
Dislike.create(user_id: u2.id, image_id: i4.id)